<?php

$labels = array();
$labels['fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Typ';
$labels['fetchmailserver'] = 'POP3/IMAP Server';
$labels['fetchmailkeep'] = 'Mails nach Empfang _nicht_ löschen';
$labels['fetchmailenabled'] = 'Aktiv';
$labels['nofetch'] = 'Keine Einträge vorhanden';
$labels['fetchmail_entries'] = 'Vorhandene Einträge';
$labels['fetchmailpollinterval'] = 'Häufigkeit der Mailboxabfrage in Minuten';
$labels['fetchmailusessl'] = 'SSL bei Abruf verwenden';
$labels['fetchmailfetchall'] = 'Alle eMails vom Server abrufen';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Wollen Sie diesen Eintrag wirklich löschen?';
$messages['fetchmaillimitreached'] = 'Limit erreicht';
$messages['textempty'] = 'Ein oder mehrere Felder sind leer';
$messages['opnotpermitted'] = 'Operation nicht gestattet!';
$messages['fetchmailnewentry'] = 'Als neuen Eintrag speichern';
$messages['fetchmailabort'] = 'Abbrechen';
$messages['successfullysaved'] = 'Erfolgreich gespeichert!';
$messages['successfullyenabled'] = 'Erfolgreich aktiviert!';
$messages['successfullydisabled'] = 'Erfolgreich deaktiviert!';
$messages['successfullydeleted'] = 'Erfolgreich gelöscht!';

?>