<?php

$labels = array();
$labels['fetchmail'] = 'Fetchmail';
$labels['fetchmailtyp'] = 'Тип сервера';
$labels['fetchmailserver'] = 'Адрес сервера';
$labels['fetchmailprotocol'] = 'Протокол';
$labels['fetchmaildelete'] = 'Удалить сообщения после загрузки';
$labels['fetchmailkeep'] = 'Не удалять сообщения на сервере';
$labels['fetchmailenabled'] = 'Включить';
$labels['nofetch'] = 'Нет записей';
$labels['fetchmail_entries'] = 'Все записи';
$labels['fetchmailpollinterval'] = 'Частота проверки';
$labels['fetchmailusessl'] = 'Использовать SSL';
$labels['fetchmailfetchall'] = 'Загружать все сообщения с сервера';

$messages = array();
$messages['fetchmaildelconfirm'] = 'Вы хотите действительно удалить эту запись?';
$messages['fetchmaillimitreached'] = 'Вы достигли ограничения';
$messages['textempty'] = 'Одно или несколько полей не заполнено';
$messages['opnotpermitted'] = 'Эта операция не допускается!';
$messages['fetchmailnewentry'] = 'Сохранить как новую запись';
$messages['fetchmailabort'] = 'Отменить';
$messages['successfullysaved'] = 'Успешно сохранено!';
$messages['successfullyenabled'] = 'Успешно включено!';
$messages['successfullydisabled'] = 'Успешно выключено!';
$messages['successfullydeleted'] = 'Успешно удалено!';

?>