<?php
//Anyone fluent in German feel free to review this file
$labels = array();
$labels['fetchmail'] = 'Fetchmail';
$labels['fetchmaildelete'] = 'Nach dem Abruf E-Mails löschen';
$labels['fetchmailenabled'] = 'Aktiv';
$labels['fetchmailfetchall'] = 'Alle E-Mails abrufen';
$labels['fetchmailfolder'] = 'Nur diesen Ordner abrufen';
$labels['fetchmailkeep'] = 'E-Mails <strong>nicht</strong> löschen';
$labels['fetchmailpollinterval'] = 'Abfrage-Intervall in Minuten';
$labels['fetchmailprotocol'] = 'Protokoll';
$labels['fetchmailserver'] = 'Server-Hostname';
$labels['fetchmailusessl'] = 'SSL aktivieren';
$labels['fetchmail_entries'] = 'Vorhandene Einträge';
$labels['fetchmail_to'] = 'Hole E-Mails von';
$labels['nofetch'] = 'Keine Einträge vorhanden';

$messages = array();
$messages['fetchmailabort'] = 'Abbrechen';
$messages['fetchmaildelconfirm'] = 'Wollen Sie diesen Eintrag wirklich löschen?';
$messages['fetchmaillimitreached'] = 'Limit erreicht';
$messages['fetchmailnewentry'] = 'Als neuen Eintrag speichern';
$messages['opnotpermitted'] = 'Operation nicht gestattet!';
$messages['successfullydeleted'] = 'Erfolgreich gelöscht!';
$messages['successfullydisabled'] = 'Erfolgreich deaktiviert!';
$messages['successfullyenabled'] = 'Erfolgreich aktiviert!';
$messages['successfullysaved'] = 'Erfolgreich gespeichert!';
$messages['textempty'] = 'Einige Felder sind leer';

?>
