<?php
//Anyone fluent in German feel free to review this file
$labels = array();
$labels['imapsync'] = 'Imapsync';
$labels['imapsyncdelete'] = 'Nach dem Abruf E-Mails löschen';
$labels['imapsyncenabled'] = 'Aktiv';
$labels['imapsyncfetchall'] = 'Alle E-Mails abrufen';
$labels['imapsyncfolder'] = 'Nur diesen Ordner abrufen';
$labels['imapsynckeep'] = 'E-Mails <strong>nicht</strong> löschen';
$labels['imapsyncpollinterval'] = 'Abfrage-Intervall in Minuten';
$labels['imapsyncprotocol'] = 'Protokoll';
$labels['imapsyncserver'] = 'Server-Hostname';
$labels['imapsyncusessl'] = 'SSL aktivieren';
$labels['imapsync_entries'] = 'Vorhandene Einträge';
$labels['imapsync_to'] = 'Hole E-Mails für';
$labels['nofetch'] = 'Keine Einträge vorhanden';
$labels['dest_password'] = 'lokales Passwort';

$messages = array();
$messages['imapsyncabort'] = 'Abbrechen';
$messages['imapsyncdelconfirm'] = 'Wollen Sie diesen Eintrag wirklich löschen?';
$messages['imapsynclimitreached'] = 'Limit erreicht';
$messages['imapsyncnewentry'] = 'Als neuen Eintrag speichern';
$messages['opnotpermitted'] = 'Operation nicht gestattet!';
$messages['successfullydeleted'] = 'Erfolgreich gelöscht!';
$messages['successfullydisabled'] = 'Erfolgreich deaktiviert!';
$messages['successfullyenabled'] = 'Erfolgreich aktiviert!';
$messages['successfullysaved'] = 'Erfolgreich gespeichert!';
$messages['textempty'] = 'Einige Felder sind leer';

?>
