<?php
//Anyone fluent in German feel free to review this file
$labels = array();
$labels['fetchmail'] = 'Fetchmail';
//$labels['fetchmaildelete'] = 'Delete emails after receiving';
$labels['fetchmailenabled'] = 'Aktiv';
$labels['fetchmailfetchall'] = 'Alle eMails vom Server abrufen';
//$labels['fetchmailfolder'] = 'Remote server folder';
$labels['fetchmailkeep'] = 'Mails nach Empfang _nicht_ löschen';
$labels['fetchmailpollinterval'] = 'Häufigkeit der Mailboxabfrage in Minuten';
//$labels['fetchmailprotocol'] = 'Protocol';
//$labels['fetchmailserver'] = 'Server hostname';
$labels['fetchmailusessl'] = 'SSL bei Abruf verwenden';
$labels['fetchmail_entries'] = 'Vorhandene Einträge';
//$labels['fetchmail_to'] = 'Collect mail to';
$labels['nofetch'] = 'Keine Einträge vorhanden';

$messages = array();
$messages['fetchmailabort'] = 'Abbrechen';
$messages['fetchmaildelconfirm'] = 'Wollen Sie diesen Eintrag wirklich löschen?';
$messages['fetchmaillimitreached'] = 'Limit erreicht';
$messages['fetchmailnewentry'] = 'Als neuen Eintrag speichern';
$messages['opnotpermitted'] = 'Operation nicht gestattet!';
$messages['successfullydeleted'] = 'Erfolgreich gelöscht!';
$messages['successfullydisabled'] = 'Erfolgreich deaktiviert!';
$messages['successfullyenabled'] = 'Erfolgreich aktiviert!';
$messages['successfullysaved'] = 'Erfolgreich gespeichert!';
$messages['textempty'] = 'Ein oder mehrere Felder sind leer';

?>