<?php

$labels = array();
$labels['fetchmail'] = 'Fetchmail';
$labels['fetchmaildelete'] = 'Delete emails after receiving';
$labels['fetchmailenabled'] = 'Enable';
$labels['fetchmailfetchall'] = 'Fetch all e-mails from server';
$labels['fetchmailfolder'] = 'Remote server folder';
$labels['fetchmailkeep'] = 'Do not remove messages from the server';
$labels['fetchmailpollinterval'] = 'Poll interval for the mailbox';
$labels['fetchmailprotocol'] = 'Protocol';
$labels['fetchmailserver'] = 'Server hostname';
$labels['fetchmailusessl'] = 'Use SSL';
$labels['fetchmail_entries'] = 'Accounts to collect from';
$labels['fetchmail_to'] = 'Collect mail to';
$labels['nofetch'] = 'No entries available';

$messages = array();
$messages['fetchmailabort'] = 'Cancel';
$messages['fetchmaildelconfirm'] = 'Do you want to delete this entry?';
$messages['fetchmaillimitreached'] = 'Limit reached';
$messages['fetchmailnewentry'] = 'Save as new';
$messages['opnotpermitted'] = 'Operation not permitted!';
$messages['successfullydeleted'] = 'Deleted successfully!';
$messages['successfullydisabled'] = 'Disabled successfully!';
$messages['successfullyenabled'] = 'Enabled successfully!';
$messages['successfullysaved'] = 'Saved successfully!';
$messages['textempty'] = 'Required fields are empty';

?>
