<?php

$labels = array();
$labels['fetchmail'] = 'Fetchmail';
$labels['fetchmaildelete'] = 'Удалить сообщения после загрузки';
$labels['fetchmailenabled'] = 'Включить';
$labels['fetchmailfetchall'] = 'Загружать все сообщения с сервера';
$labels['fetchmailfolder'] = 'Папка на удалённом сервере';
$labels['fetchmailkeep'] = 'Не удалять сообщения на сервере';
$labels['fetchmailpollinterval'] = 'Частота проверки';
$labels['fetchmailprotocol'] = 'Протокол';
$labels['fetchmailserver'] = 'Адрес сервера';
$labels['fetchmailusessl'] = 'Использовать SSL';
$labels['fetchmail_entries'] = 'Учётные записи для сбора почты';
$labels['fetchmail_to'] = 'Собирать почту в';
$labels['nofetch'] = 'Нет записей';
$labels['dest_password'] = 'локальный пароль';
$labels['imapsyncskipemptyfolders'] = 'оставить пустые папки';
$labels['imapsyncsubscribeall'] = 'все подписаться папку';
$labels['imapsyncmaxage'] = 'Максимальный возраст объектов (дней)';

$messages = array();
$messages['fetchmailabort'] = 'Отменить';
$messages['fetchmaildelconfirm'] = 'Вы действительно хотите удалить эту запись?';
$messages['fetchmaillimitreached'] = 'Вы достигли ограничения';
$messages['fetchmailnewentry'] = 'Сохранить как новую запись';
$messages['opnotpermitted'] = 'Эта операция не разрешена!';
$messages['successfullydeleted'] = 'Успешно удалено!';
$messages['successfullydisabled'] = 'Успешно отключено!';
$messages['successfullyenabled'] = 'Успешно включено!';
$messages['successfullysaved'] = 'Успешно сохранено!';
$messages['textempty'] = 'Не заполнены обязательные поля';

?>
